# Generated by Django 4.1.6 on 2023-02-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_messowner_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_roomOwner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
