# Generated by Django 4.1.6 on 2023-02-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_remove_profile_is_roomowner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessOwner',
            new_name='Owner',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('owner', 'Owner')], default='student', max_length=10),
        ),
    ]
