# Generated by Django 4.1.7 on 2023-02-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_rename_messowner_owner_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
