# Generated by Django 4.1.7 on 2023-02-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='mess_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='institute',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
