# Generated by Django 4.1.7 on 2023-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_feedback_owner_address_owner_bedavailable_owner_rent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
