# Generated by Django 4.1.7 on 2023-02-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_review_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, default='bydefault.jpg', null=True, upload_to='media'),
        ),
    ]
