# Generated by Django 4.1.7 on 2023-03-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_profile_dp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_user_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('date_of_post', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
