# Generated by Django 4.1.7 on 2023-03-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_tutorial_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='topic',
            field=models.CharField(max_length=500),
        ),
    ]
