# Generated by Django 4.1.7 on 2023-03-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_institute_delete_visitcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.ImageField(upload_to='media/notice')),
            ],
        ),
    ]
