# Generated by Django 4.1.7 on 2023-03-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.institute'),
        ),
    ]
