# Generated by Django 4.1.7 on 2023-03-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_notice_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date_of_post',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
