# Generated by Django 4.1.7 on 2023-03-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_notice_date_of_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='student',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
