# Generated by Django 4.1.7 on 2023-04-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0020_institute_institute_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='Institute',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Institute',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
