# Generated by Django 4.1.7 on 2023-04-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0021_owner_institute_teacher_institute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Institute',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Institute',
            new_name='institute',
        ),
    ]
