# Generated by Django 4.1.7 on 2023-04-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0022_rename_institute_owner_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_userid',
            field=models.IntegerField(),
        ),
    ]
