# Generated by Django 4.1.7 on 2023-04-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0023_alter_student_student_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='mess_userid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_userid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='poster_user_id',
            field=models.IntegerField(),
        ),
    ]
